<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="rs-MAC15.local" failures="2" tests="9" name="RetryMulitpleFailedTestCases" time="0.055" errors="0" timestamp="15 Jun 2018 06:28:51 GMT">
  <testcase classname="RetryLogic.MyTests" name="Test1" time="0.012">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="RetryLogic.MyTests" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="RetryLogic.MyTests" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="RetryLogic.MyTests" name="Test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]at RetryLogic.MyTests.Test1(MyTests.java:14)... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="RetryLogic.MyTests" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="RetryLogic.MyTests" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="RetryLogic.MyTests" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="RetryLogic.MyTests" name="Test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]at RetryLogic.MyTests.Test2(MyTests.java:20)... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="RetryLogic.MyTests" name="Test3" time="0.001"/>
</testsuite> <!-- RetryMulitpleFailedTestCases -->
