<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-06-28T15:21:14Z" name="Suite" finished-at="2018-06-28T15:21:28Z" duration-ms="14104">
    <groups>
    </groups>
    <test started-at="2018-06-28T15:21:14Z" name="Test" finished-at="2018-06-28T15:21:28Z" duration-ms="14104">
      <class name="ScreenshotForFailedTest.ScreenshotTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:ScreenshotForFailedTest.ScreenshotTest@16a0ee18]" started-at="2018-06-28T20:51:14Z" name="setUp" finished-at="2018-06-28T20:51:18Z" duration-ms="4440" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="test1()[pri:0, instance:ScreenshotForFailedTest.ScreenshotTest@16a0ee18]" started-at="2018-06-28T20:51:18Z" name="test1" finished-at="2018-06-28T20:51:18Z" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ScreenshotForFailedTest.ScreenshotTest@16a0ee18]" started-at="2018-06-28T20:51:18Z" name="tearDown" finished-at="2018-06-28T20:51:18Z" duration-ms="76" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:ScreenshotForFailedTest.ScreenshotTest@16a0ee18]" started-at="2018-06-28T20:51:18Z" name="setUp" finished-at="2018-06-28T20:51:23Z" duration-ms="4469" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="test2()[pri:0, instance:ScreenshotForFailedTest.ScreenshotTest@16a0ee18]" started-at="2018-06-28T20:51:23Z" name="test2" finished-at="2018-06-28T20:51:23Z" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at ScreenshotForFailedTest.ScreenshotTest.test2(ScreenshotTest.java:32)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ScreenshotForFailedTest.ScreenshotTest@16a0ee18]" started-at="2018-06-28T20:51:23Z" name="tearDown" finished-at="2018-06-28T20:51:23Z" duration-ms="81" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:ScreenshotForFailedTest.ScreenshotTest@16a0ee18]" started-at="2018-06-28T20:51:23Z" name="setUp" finished-at="2018-06-28T20:51:28Z" duration-ms="4353" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="test3()[pri:0, instance:ScreenshotForFailedTest.ScreenshotTest@16a0ee18]" started-at="2018-06-28T20:51:28Z" name="test3" finished-at="2018-06-28T20:51:28Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ScreenshotForFailedTest.ScreenshotTest@16a0ee18]" started-at="2018-06-28T20:51:28Z" name="tearDown" finished-at="2018-06-28T20:51:28Z" duration-ms="73" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ScreenshotForFailedTest.ScreenshotTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
